### PR TITLE
commit

### PR DESCRIPTION
**Pull request by awettedla**
can anyone approved it thanks

### CODE REVIEW

**Review by ozdenabdulaziz — CHANGES_REQUESTED** [review]
Check line 30 in your code.

you need to search for something... 

example: search.sendKeys("G.Ronaldo").click();  ---> it's only example you need to write your code like this.

**Comment by awettedla** [comment]
I fixed it

**Review by awettedla — COMMENTED** [review]
good

**Comment by awettedla** [comment]
.

**Review by AnaKeane — APPROVED** [review]
yes

**Review by ozdenabdulaziz — APPROVED** [review]

**Pull request merged**
